In [1]:
import torch
torch.__version__

'2.6.0'

## Tensors
- fundamental building blocks of machine learning
- multidimensional array

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Vector
vector = torch.tensor([7,7])
print(vector, vector.ndim, vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [5]:
matrix = torch.tensor([[7,7],[8, 8]])
print(matrix, matrix.ndim, matrix.shape)

tensor([[7, 7],
        [8, 8]]) 2 torch.Size([2, 2])


In [6]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[1.7056e-01, 1.9612e-01, 6.3244e-01, 1.7250e-01],
         [3.7622e-01, 9.1637e-01, 1.3717e-01, 3.3287e-02],
         [3.3402e-04, 8.7128e-01, 2.4122e-01, 3.4028e-01]]),
 torch.float32)

In [7]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
random_tensor

tensor([[1.7056e-01, 1.9612e-01, 6.3244e-01, 1.7250e-01],
        [3.7622e-01, 9.1637e-01, 1.3717e-01, 3.3287e-02],
        [3.3402e-04, 8.7128e-01, 2.4122e-01, 3.4028e-01]])

In [11]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
zero_to_ten = torch.arange(start=0, end=15, step=3)
zero_to_ten

tensor([ 0,  3,  6,  9, 12])

In [14]:
torch.zeros_like(zero_to_ten)

tensor([0, 0, 0, 0, 0])

In [15]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
tensor = torch.tensor([1, 3 , 5, 7, 9])
tensor.size()

torch.Size([5])

In [19]:
tensor * tensor

tensor([ 1,  9, 25, 49, 81])

In [21]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

tensor_A, tensor_B, tensor_B.T

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [23]:
tensor_A.shape, tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [26]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [27]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [28]:
x = torch.arange(0, 100, 10)
x.min(), x.max(), x.sum(), x.type(torch.float32).mean()

(tensor(0), tensor(90), tensor(450), tensor(45.))

In [29]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

In [30]:
x = torch.arange(1., 8)

In [31]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [34]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [35]:
x_stacked = torch.stack([x, x, x, x, x])
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([5, 7]))

In [36]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [37]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [38]:
print(x[:, 0], x[:, :, 1])

tensor([[1, 2, 3]]) tensor([[2, 5, 8]])


In [39]:
import numpy as np

In [42]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [43]:
random_tensor_A = torch.rand(size=(3, 4))
random_tensor_B = torch.rand(size=(3, 4))

random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [44]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [46]:
torch.cuda.is_available()

False

In [47]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [48]:
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [49]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [50]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [51]:
device

'mps'

In [52]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [53]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercise
https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb